package Presentacio;

/**
 * Created by USUARIO on 12/05/2015.
 */
public class VistaAltaEvento extends javax.swing.JFrame{

        /**
         * Creates new form NewJFrame
         */
        public VistaAltaEvento() {
            initComponents();
        }

        public void inicializar() {
            limpiarcampos();
        }

        private void limpiarcampos() {
            this.ctnombre.setText("");
            this.ctfecha.setText("");
            this.ctimportancia.setText("");
            cbtipo.setSelectedIndex(0);
            lbinfo.setVisible(false);
        }

        private void mostrarmensaje(String s) {
            lbinfo.setVisible(true);
            lbinfo.setText(s);
        }

        private boolean validar(String nombre, String fecha, String importancia, int i) {
            return !nombre.equals("") && !fecha.equals("") && !importancia.equals("") && i != 0;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            lbtitulo = new javax.swing.JLabel();
            lbnombre = new javax.swing.JLabel();
            lbfecha = new javax.swing.JLabel();
            lbimportancia = new javax.swing.JLabel();
            lbtipo = new javax.swing.JLabel();
            ctnombre = new javax.swing.JTextField();
            ctfecha = new javax.swing.JTextField();
            ctimportancia = new javax.swing.JTextField();
            cbtipo = new javax.swing.JComboBox();
            btguardar = new javax.swing.JButton();
            btlimpiar = new javax.swing.JButton();
            lbinfo = new javax.swing.JLabel();
            btcerrar = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            lbtitulo.setText("Alta de un evento");

            lbnombre.setText("Nombre:");

            lbfecha.setText("Fecha:");

            lbimportancia.setText("Importancia:");

            lbtipo.setText("Tipo:");

            ctnombre.setText("");

            ctfecha.setText("");

            ctimportancia.setText("");

            cbtipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un tipo", "Votación", "Reunión Profesional", "Reunión Personal", "Acto Oficial", "Acto No Oficial" }));

            btguardar.setText("Guardar");
            btguardar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btguardarActionPerformed(evt);
                }
            });

            btlimpiar.setText("Limpiar");
            btlimpiar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btlimpiarActionPerformed(evt);
                }
            });

            btcerrar.setText("Cerrar");
            btcerrar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btcerrarActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(33, 33, 33)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(lbinfo)
                                                                            .addGroup(layout.createSequentialGroup()
                                                                                    .addComponent(btguardar)
                                                                                    .addGap(72, 72, 72)
                                                                                    .addComponent(btlimpiar)))
                                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                    .addGroup(layout.createSequentialGroup()
                                                                                            .addComponent(lbimportancia)
                                                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                    .addGroup(layout.createSequentialGroup()
                                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                    .addComponent(lbfecha, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addComponent(lbnombre, javax.swing.GroupLayout.Alignment.LEADING))
                                                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                            .addGroup(layout.createSequentialGroup()
                                                                                    .addComponent(lbtipo)
                                                                                    .addGap(114, 114, 114)))
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addComponent(btcerrar)
                                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                            .addComponent(ctnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                                                                            .addComponent(ctfecha)
                                                                                            .addComponent(ctimportancia)))))))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lbtitulo)
                                                    .addGap(90, 90, 90)))
                                    .addGap(93, 93, 93))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(lbtitulo)
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbnombre)
                                            .addComponent(ctnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbfecha)
                                            .addComponent(ctfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbimportancia)
                                            .addComponent(ctimportancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbtipo)
                                            .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(lbinfo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btguardar)
                                            .addComponent(btlimpiar)
                                            .addComponent(btcerrar))
                                    .addGap(27, 27, 27))
            );

            pack();
        }// </editor-fold>

        private void btlimpiarActionPerformed(java.awt.event.ActionEvent evt) {
            limpiarcampos();
        }

        private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {

            String nombre = ctnombre.getText();
            String fecha = ctfecha.getText();
            String importanciaStr = ctimportancia.getText();
            if (!validar(nombre, fecha, importanciaStr, cbtipo.getSelectedIndex())) {
                mostrarmensaje("Debe ingresar todos los campos");
                return;
            }
            try {
                int importancia = Integer.parseInt(importanciaStr);
                String tipo = (String) cbtipo.getSelectedItem();
                limpiarcampos();
                mostrarmensaje("Evento creado");
            }
            catch(Exception e) {
                mostrarmensaje("Error en el ingreso");
            }
        }

        private void btcerrarActionPerformed(java.awt.event.ActionEvent evt) {
            dispose();
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(VistaAltaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(VistaAltaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(VistaAltaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(VistaAltaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>

        /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new VistaAltaEvento().setVisible(true);
                }
            });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton btcerrar;
        private javax.swing.JButton btguardar;
        private javax.swing.JButton btlimpiar;
        private javax.swing.JComboBox cbtipo;
        private javax.swing.JTextField ctfecha;
        private javax.swing.JTextField ctimportancia;
        private javax.swing.JTextField ctnombre;
        private javax.swing.JLabel lbfecha;
        private javax.swing.JLabel lbimportancia;
        private javax.swing.JLabel lbinfo;
        private javax.swing.JLabel lbnombre;
        private javax.swing.JLabel lbtipo;
        private javax.swing.JLabel lbtitulo;
        // End of variables declaration
    }
